## Basic Commands in Python

#### 0. Python Coding & Jupyter Notebook Basics
- Code vs. Markdown
- To run code (Enter + Shift)
- Insert cells
- (Almost) always case sensitive

In [ ]:
print("Hello, World!")

Hello, World!

#### 1. Arithmetic

- Arithmetic follows the normal conventions you've used all your life: `+`,`-`,`/`, `*`.
- To compute powers, use the `**` operator. 
- Parentheses can/should be used for grouping.
- Use `_` for the last printed expression

In [2]:
1 + 1

2

In [3]:
a = 1
a

1

In [4]:
b = 1 + 1
b

2

In [6]:
c = a + b
c

3

In [ ]:
d = A + B
# this won't work bc uppercase letters are not defined

NameError: name 'A' is not defined

In [ ]:
_ + 1
# this will work because it will add to the last output, which was 3

4

#### 2. Comparisons

Comparisons allow you to evaluate whether a statement is true or false.  You can also use this later for indicator variables, among many other useful tools.  A couple notes:
 - The operators `>` and `<` work as you'd expect.
 - ! means not.
 - Use `=` and `==` differently.  The equal sign (`=`) assigns variables, whereas `==` is a comparison operator.

In [9]:
1 == 1

True

In [10]:
5 > 1

True

In [11]:
5 < 1

False

In [13]:
1 != 2

True

In [14]:
1 == 1 and 2 > 1

True

#### 3. Data types
We will mainly focus on three data types: integer numbers (int), non-integer numbers (float), and text strings (str).

In [15]:
x = 12

In [16]:
type(x)

int

In [18]:
y = 1.2
type(y)

float

In [21]:
z = "accounting" # single and double quotes are interchangeable
z

'accounting'

In [22]:
type(z)

str

In [25]:
z[0] # just interested in the first character of the string (remember 0 means first)
z[1]

'c'

In [33]:
z[:2] # this is a slice, return first two characters of the string bc the second number is not included in the slice

'ac'

In [36]:
z[-2:] # this is a slice, return last two characters of the string bc negative means count from end of the string

'ng'

#### 4. Import libraries
A Python library is a collection of pre-written, reusable code components—such as functions, classes, and modules—that allow users to perform specific tasks without writing the logic completely from scratch.

In [37]:
import pandas as pd
import numpy as np
import datetime as dt

#### What is Numpy
Numpy is one of the fundamental Python packages for data science because of its ability to manipulate numerical data. Many other packages in the PyData ecosystem are built upon Numpy, including Pandas. Numpy is shorthand for "numerical Python."

#### What is Pandas
Pandas is one of the most popular data manipulation and analysis libraries. It provides intuitive, high-performance data structures—like DataFrames (tables) and Series (lists)—that make cleaning, transforming, and analyzing large datasets feel just like working in Excel.

*You need to install Numpy and Pandas before moving on.  They should be included with your Anaconda installation.*

#### 5. Data structures
A data structure is a specialized format for organizing, managing, and storing data so it can be accessed and modified efficiently. We will primarily focus on (1) lists, (2) series, and (3) dataframes.

##### 5.1 Lists
A list is a built-in data structure used to store an ordered, mutable (changeable) collection of items inside square brackets [], with each item separated by a comma.
Items DO NOT have to be of the same data type.

In [39]:
numbers = [1, 2, 3, 4]
numbers

[1, 2, 3, 4]

In [41]:
letters = ['a', 'b', 'c', 'd'] # again single or double quotes are interchangeable
letters

['a', 'b', 'c', 'd']

In [54]:
mixed = [1, 'b', 3, 'd']
mixed

[1, 'b', 3, 'd']

In [46]:
list = [a, b, c] # list storing variables (d wouldn't work bc it wasn't define, there was an error)
list

[1, 2, 3]

##### 5.2 Series
A series is a one-dimensional data structure provided by Pandas. It can hold data of any data type, such as int, str (denoted object), and float. The series has a few advantages over lists: it is extremely fast and memory-efficient, can handle missing values, and better supports math operations.

In [ ]:
a1 = pd.Series([1, 2, 3, 4])
a1 # print result is different from lists, bc there is an index on the left and the datatype below

0    1
1    2
2    3
3    4
dtype: int64

In [ ]:
b1 = pd.Series(['a', 'b', 'c', 'd'])
b1 # data type is object, which a broader term for strings

0    a
1    b
2    c
3    d
dtype: object

In [51]:
c1 = pd.Series([1, "b", 3, "d"])
c1 # data type is object bc strings are a part of it

0    1
1    b
2    3
3    d
dtype: object

In [ ]:
a2 = a1 + 2 # adds two to each item in the series
a2

0    3
1    4
2    5
3    6
dtype: int64

In [ ]:
numbers2 = numbers + 2 # this will not work bc you can't add a number to a list, but you can add a number to a series

TypeError: can only concatenate list (not "int") to list

##### 5.3 DataFrames
A Python DataFrame is a two-dimensional, tabular data structure that functions similarly to an Excel spreadsheet/table.

In [64]:
# creating a dataframe using pandas library, the pd.DataFrame() function must be typed like that
df = pd.DataFrame({
    'id':['1', '2', '3'], # in class we won't have to type, we'll rly j import data as a dataframe
    'price':[10, 5, 8]
})
df

  id  price
0  1     10
1  2      5
2  3      8

In [ ]:
# say the prices all went up by 1, we can add 1 to the price column
df['price'] + 1 # square bracket selects a column within dataframe "df"

0    11
1     6
2     9
Name: price, dtype: int64

In [ ]:
df # see how it didn't change the original dataframe and just printed the new values?

  id  price
0  1     10
1  2      5
2  3      8

In [68]:
df['price'] = df['price'] + 1 # this will change the original dataframe, bc we are assigning the new values to the column
df

  id  price
0  1     11
1  2      6
2  3      9

#### 6. Methods
A method is a function that is explicitly tied to an object or class. We will apply the following methods to DataFrames:

- .copy()
- .info()
- .head()
- .tail()
- .describe()

*[these are specific to pandas]*

In [72]:
# copy() creates a copy of the dataframe. Note how its not like excel where you have to have an argument, this function will j go
df2 = df.copy()
df2

  id  price
0  1     11
1  2      6
2  3      9

In [ ]:
df3 = pd.DataFrame({
    'id':['1', '2', '3', '4'],
    'price':[10, 5, 8, np.nan] # nan here means missing value (like null), it's from numpy library saved as np
})
df3

  id  price
0  1   10.0
1  2    5.0
2  3    8.0
3  4    NaN

In [ ]:
# info() gives basic summary of the dataframe' structure
df3.info()  # the dtype for the price column is float64 bc it has a missing value, which is a float

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      4 non-null      object
 1   price   3 non-null      float64
dtypes: float64(1), object(1)
memory usage: 196.0+ bytes

In [ ]:
# head() and tail() show first few and last few rows of the dataframe
df3.head(3) # by default with no argument, it's 5 rows, but you can specify with a number

  id  price
0  1   10.0
1  2    5.0
2  3    8.0

In [ ]:
df3.tail(2) # last two rows (5 default again)

  id  price
2  3    8.0
3  4    NaN

In [ ]:
# 2 ways to use:
df3.describe()  # gives summary statistics for all numerical columns

           price
count   3.000000
mean    7.666667
std     2.516611
min     5.000000
25%     6.500000
50%     8.000000
75%     9.000000
max    10.000000

In [84]:
df3['price'].describe() # gives summary statistics for just the price column

count     3.000000
mean      7.666667
std       2.516611
min       5.000000
25%       6.500000
50%       8.000000
75%       9.000000
max      10.000000
Name: price, dtype: float64

#### 7. Control flows
Controls the exact order in which individual code statements are executed or evaluated at runtime. We will focus on (1) conditional statements and (2) loops.

##### 7.1 The `if` and `elif` statement

##### 7.2 The `for` statement